#!/usr/bin/env python3
"""Builds landing/privacy.html and landing/terms.html from the app's own legal text.

Google Play requires a publicly reachable privacy policy URL, and the App Store asks
for both documents. Retyping them into HTML would create a second copy that drifts —
and the one that drifts is the one a regulator reads. So the pages are generated from
`shared/.../i18n/LegalTexts*.kt`, which is what the app itself renders.

    python3 tools/gen_legal_pages.py

Re-run it whenever the Kotlin text changes; the pages carry a header saying so.
"""

from __future__ import annotations

import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
I18N = ROOT / "shared/src/commonMain/kotlin/uz/sadora/app/i18n"
OUT = ROOT / "landing"

LANGUAGES = [
    ("uz", "LegalTextsUz.kt", "O‘zbekcha"),
    ("ru", "LegalTextsRu.kt", "Русский"),
    ("en", "LegalTextsEn.kt", "English"),
]

DOCUMENTS = [
    ("terms", "terms"),
    ("privacy", "privacy"),
]


def literals(source: str) -> list[str]:
    """Kotlin string literals in order, with `"a" + "b"` folded into one."""
    folded = re.sub(r'"\s*\+\s*\n?\s*"', "", source)
    found = re.findall(r'"((?:[^"\\]|\\.)*)"', folded)
    return [item.replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\") for item in found]


def balanced(source: str, start: int) -> str:
    """The text between the parenthesis at [start] and the one that closes it."""
    depth, index, in_string, escaped = 0, start, False, False
    while index < len(source):
        char = source[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return source[start + 1 : index]
        index += 1
    raise ValueError("unbalanced parentheses")


def sections(source: str, name: str) -> list[tuple[str, list[str]]]:
    marker = f"override val {name} = listOf"
    body = balanced(source, source.index("(", source.index(marker)))
    out = []
    for match in re.finditer(r"LegalSection\s*\(", body):
        block = balanced(body, match.end() - 1)
        heading, *paragraphs = literals(block)
        out.append((heading, paragraphs))
    return out


def value(source: str, name: str) -> str | None:
    match = re.search(
        rf'override val {name}(?:: String\?)?\s*=\s*(?:"((?:[^"\\]|\\.)*)"|null)', source
    )
    if match is None or match.group(1) is None:
        return None
    return match.group(1).replace('\\"', '"')


def page(document: str, language: str, label: str, source: str, others: list[tuple[str, str]]) -> str:
    title = value(source, f"{document}Title") or document
    effective = value(source, "effectiveDate") or ""
    notice = value(source, "translationNotice")
    date_label = {"uz": "Kuchga kirgan sana", "ru": "Дата вступления в силу", "en": "Effective date"}[language]
    other_doc = "privacy" if document == "terms" else "terms"
    other_name = value(source, f"{other_doc}Title") or other_doc

    body = []
    for heading, paragraphs in sections(source, document):
        body.append(f"<h2>{html.escape(heading)}</h2>")
        body.extend(f"<p>{html.escape(paragraph)}</p>" for paragraph in paragraphs)

    switcher = " · ".join(
        f'<strong>{html.escape(name)}</strong>' if code == language
        else f'<a href="{document}.{code}.html">{html.escape(name)}</a>'
        for code, name in others
    )

    return f"""<!doctype html>
<html lang="{language}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} — SADORA</title>
<meta name="robots" content="index, follow">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<!-- Generated by tools/gen_legal_pages.py from shared/.../i18n/LegalTexts*.kt.
     Edit the Kotlin and re-run; a hand edit here becomes the copy that drifts. -->
<style>
:root {{
  color-scheme: light dark;
  --bg: #F7F5FF; --surface: #FFFFFF; --text: #1A1630; --muted: #6F6A8A;
  --muted-2: #9590AD; --line: #EAE6FA; --ink: #6247E0;
}}
@media (prefers-color-scheme: dark) {{
  :root {{ --bg: #0E0B1F; --surface: #17132E; --text: #F2F0FA; --muted: #B6B1CC;
           --muted-2: #8B85A6; --line: #2A2448; --ink: #B9A6FF; }}
}}
* {{ box-sizing: border-box; }}
body {{
  margin: 0; background: var(--bg); color: var(--text);
  font: 16px/1.65 'Figtree', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  -webkit-text-size-adjust: 100%;
}}
.wrap {{ max-width: 720px; margin: 0 auto; padding: 32px 20px 72px; }}
a {{ color: var(--ink); }}
header {{ border-bottom: 1px solid var(--line); padding-bottom: 20px; margin-bottom: 28px; }}
.brand {{ font-weight: 700; letter-spacing: .18em; text-transform: uppercase; font-size: 13px; color: var(--muted); }}
h1 {{ font-size: 30px; line-height: 1.2; margin: 10px 0 12px; }}
h2 {{ font-size: 18px; margin: 32px 0 8px; }}
p {{ margin: 0 0 10px; color: var(--muted); }}
.meta {{ font-size: 13px; color: var(--muted-2); margin: 0 0 4px; }}
.switch {{ font-size: 13px; color: var(--muted-2); margin-top: 12px; }}
footer {{ margin-top: 44px; padding-top: 20px; border-top: 1px solid var(--line); font-size: 13px; color: var(--muted-2); }}
</style>
</head>
<body>
<div class="wrap">
<header>
  <div class="brand">SADORA</div>
  <h1>{html.escape(title)}</h1>
  <p class="meta">{date_label}: {html.escape(effective)}</p>
  {f'<p class="meta">{html.escape(notice)}</p>' if notice else ''}
  <div class="switch">{switcher}</div>
</header>
{chr(10).join(body)}
<footer>
  <a href="{other_doc}.{language}.html">{html.escape(other_name)}</a> ·
  <a href="index.html">sadora.uz</a> ·
  <a href="mailto:privacy@sadora.uz">privacy@sadora.uz</a>
</footer>
</div>
</body>
</html>
"""


def main() -> int:
    sources = {code: (I18N / filename).read_text(encoding="utf-8") for code, filename, _ in LANGUAGES}
    names = [(code, label) for code, _, label in LANGUAGES]
    written = []
    for document, _ in DOCUMENTS:
        for code, _, _ in LANGUAGES:
            target = OUT / f"{document}.{code}.html"
            target.write_text(page(document, code, "", sources[code], names), encoding="utf-8")
            written.append(target.name)
        # The bare name is the URL that goes into Play Console and App Store Connect.
        canonical = OUT / f"{document}.html"
        canonical.write_text((OUT / f"{document}.uz.html").read_text(encoding="utf-8"), encoding="utf-8")
        written.append(canonical.name)
    print("\n".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
