#!/usr/bin/env python3
"""Generates the two colder launcher icons from the warm one.

The app icon changes with the streak: warm while she is opening the app often, calm
while a shorter run is going, and cold once it has lapsed. Three icons therefore have
to exist as resources, because Android switches between whole `activity-alias` entries
rather than tinting one.

They are generated rather than hand-drawn for the reason every derived asset in this
repository is: the mark is one path, and three hand-maintained copies of a 3 KB path
would be three copies that stop matching the first time the brand is retouched. Only
the colours differ, so only the colours are substituted.

    python3 tools/gen_icon_moods.py

Writes:
    sadora-client/androidApp/src/main/res/drawable-v24/ic_launcher_foreground_calm.xml
    sadora-client/androidApp/src/main/res/drawable-v24/ic_launcher_foreground_cold.xml
    sadora-client/androidApp/src/main/res/drawable/ic_launcher_background_calm.xml
    sadora-client/androidApp/src/main/res/drawable/ic_launcher_background_cold.xml
    sadora-client/androidApp/src/main/res/mipmap-anydpi-v26/ic_launcher_{calm,cold}.xml
"""

from __future__ import annotations

import pathlib
import sys

try:
    from PIL import Image, ImageEnhance
except ImportError:  # pragma: no cover - the vectors are the important half
    Image = None

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "sadora-client/androidApp/src/main/res"

FOREGROUND = RES / "drawable-v24/ic_launcher_foreground.xml"
BACKGROUND = RES / "drawable/ic_launcher_background.xml"

# The warm icon's palette, and what each mood replaces it with.
#
# Calm keeps the brand's hues and only cools them: a shorter streak is still a streak,
# and an icon that punished a two-day run would be a strange thing to ship in an app
# about being kind to yourself. Cold drops the saturation almost entirely — that is the
# state of an app nobody has opened in days, and it should read as dormant, not broken.
MOODS = {
    "calm": {
        # foreground: the S gradient and the dot
        "#FFB06CFF": "#FF8E86E8",
        "#FF8A8CFF": "#FF7C93E0",
        "#FFF68CCB": "#FFC091CE",
        # background: the violet ground and the glow above the mark
        "#FF2A1D5C": "#FF241E46",
        "#FF0E0B1F": "#FF0C0B18",
        "#8CB06CFF": "#59A08CE8",
        "#00B06CFF": "#00A08CE8",
    },
    "cold": {
        "#FFB06CFF": "#FF7C8494",
        "#FF8A8CFF": "#FF6E7A8C",
        "#FFF68CCB": "#FF8A8F9C",
        "#FF2A1D5C": "#FF1C2029",
        "#FF0E0B1F": "#FF0A0C10",
        # The glow goes out entirely: a fully transparent pair is the honest way to
        # remove a radial gradient without deleting the path the mark is positioned by.
        "#8CB06CFF": "#00808A99",
        "#00B06CFF": "#00808A99",
    },
}

# How much colour survives, and how bright the result is, for the pre-26 bitmaps.
#
# Android 8 and later draw the adaptive vectors above; 7.x has only these PNGs, and an
# icon that changed on a new phone but not on an old one would be a bug someone would
# eventually report. Same two moods, applied to pixels instead of gradient stops.
BITMAP_MOODS = {
    "calm": {"saturation": 0.72, "brightness": 0.92},
    "cold": {"saturation": 0.18, "brightness": 0.68},
}

DENSITIES = ("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi")

ALIAS = """<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by tools/gen_icon_moods.py — edit the warm icon and re-run, never this file.

  The {mood} face of the launcher icon. Which one the phone shows is decided by the
  streak and applied by enabling one activity-alias at a time.
-->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background_{mood}" />
    <foreground android:drawable="@drawable/ic_launcher_foreground_{mood}" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""

BANNER = (
    "<!--\n"
    "  Generated by tools/gen_icon_moods.py from {source}.\n"
    "  Edit the warm icon and re-run; changes made here are overwritten.\n"
    "-->\n"
)


def derive(source: pathlib.Path, target: pathlib.Path, palette: dict[str, str]) -> None:
    text = source.read_text()
    missing = [colour for colour in palette if colour not in text]
    for colour, replacement in palette.items():
        text = text.replace(colour, replacement)
    # The banner goes after the XML declaration, which must stay on line one.
    head, _, tail = text.partition("\n")
    target.write_text(head + "\n" + BANNER.format(source=source.name) + tail)
    if missing:
        print(f"  ! {target.name}: {len(missing)} colour(s) not found — {', '.join(missing)}")
    print(f"  {target.relative_to(ROOT)}")


def derive_bitmaps(mood: str, settings: dict[str, float]) -> None:
    """Recolours the legacy launcher PNGs for one mood, at every density."""
    if Image is None:
        print("  (Pillow is not installed — skipping the pre-26 bitmaps)")
        return
    for density in DENSITIES:
        for base in ("ic_launcher", "ic_launcher_round"):
            source = RES / f"mipmap-{density}/{base}.png"
            if not source.exists():
                continue
            image = Image.open(source).convert("RGBA")
            # Alpha is set aside and put back: both enhancers work on the colour
            # channels, and a round icon's mask must survive the transform intact.
            alpha = image.getchannel("A")
            colour = image.convert("RGB")
            colour = ImageEnhance.Color(colour).enhance(settings["saturation"])
            colour = ImageEnhance.Brightness(colour).enhance(settings["brightness"])
            colour.putalpha(alpha)
            target = source.with_name(f"{base}_{mood}.png")
            colour.save(target)
    print(f"  mipmap-*/ic_launcher[_round]_{mood}.png")


def main() -> int:
    if not FOREGROUND.exists() or not BACKGROUND.exists():
        print("The warm icon is missing; nothing to derive from.", file=sys.stderr)
        return 1

    for mood, palette in MOODS.items():
        foreground = {k: v for k, v in palette.items() if k in FOREGROUND.read_text()}
        background = {k: v for k, v in palette.items() if k in BACKGROUND.read_text()}
        derive(FOREGROUND, FOREGROUND.with_name(f"ic_launcher_foreground_{mood}.xml"), foreground)
        derive(BACKGROUND, BACKGROUND.with_name(f"ic_launcher_background_{mood}.xml"), background)
        alias = RES / f"mipmap-anydpi-v26/ic_launcher_{mood}.xml"
        alias.write_text(ALIAS.format(mood=mood))
        print(f"  {alias.relative_to(ROOT)}")
        derive_bitmaps(mood, BITMAP_MOODS[mood])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
